### ISSUE TITLE
uid detection could fail

### ISSUE THREAD

**Issue by mattf** [radanalyticsio/base-notebook#1]
https://github.com/radanalyticsio/base-notebook/blob/master/start.sh#L21

if the uid is 1001 and not in /etc/passwd, the nss_wrapper setup will be incorrectly skipped.

this was encountered in oshinko-s2i (https://github.com/radanalyticsio/oshinko-s2i/issues/94).

cc @tmckayus @willb

**Comment by willb** [comment]
@mattf I think I inadvertently fixed this when I rebased the image FROM `radanalyticsio/openshift-spark`.  PTAL?

**Comment by mattf** [comment]
agreed. the use of entrypoint instead of custom code.
